# Generated by Django 2.0.6 on 2021-09-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0002_auto_20210929_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='nombre',
            new_name='mascotanom',
        ),
    ]
