# Generated by Django 2.0.6 on 2021-09-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0003_auto_20210929_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='peso',
            new_name='pesomascota',
        ),
    ]
