# Generated by Django 2.0.6 on 2021-09-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0005_auto_20210929_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('pk_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nombreani', models.CharField(max_length=50)),
                ('edadani', models.CharField(max_length=2)),
                ('razaani', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='mascota',
        ),
    ]
